### ISSUE TITLE
Running with debug doesn't wait for inputs

### ISSUE THREAD

**Issue by pyjames** [aaronduino/asciidots#15]
When interpreting with the -d tag, there's no prompt for an input and the interpreter crashes as if an empty string was input.
Everything works fine without the -d tag. Adding the -w tag fixes it, but outputs aren't preserved.
Here's the crash message it gives when it gets to an input:
```
$ python __main__.py samples/factor.dots -d -a 0.1
Traceback (most recent call last):
  File "__main__.py", line 257, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "__main__.py", line 253, in main
    raise e
  File "__main__.py", line 249, in main
    interpreter.run()
  File "/home/james/Documents/asciidots/dots/interpreter.py", line 40, in run
    dot.simulate_tick()
  File "/home/james/Documents/asciidots/dots/dot.py", line 79, in simulate_tick
    self.state.run(char)
  File "/home/james/Documents/asciidots/dots/states.py", line 9, in _decorator
    func(self, *args, **kwargs)
  File "/home/james/Documents/asciidots/dots/states.py", line 169, in run
    self.parent.value = int(self.parent.callbacks.get_input())
  File "__main__.py", line 73, in get_input
    return self.curses_input(self.stdscr, curses.LINES - 2, 2, '?: ')
  File "__main__.py", line 78, in curses_input
    stdscr.addstr(r + 1, c, " " * (curses.COLS - 1))
_curses.error: addwstr() returned ERR
```
Very nice language by the way, lots of fun 😃

**Comment by aaronduino** [comment]
Have fun with AsciiDots
