### ISSUE TITLE
asciidots.exe doesn't start on Python 3.7

### ISSUE THREAD

**Issue by TheBlocks** [aaronduino/asciidots#66]
I installed asciidots with `pip install asciidots` on Python 3.7.
If I try to do `asciidots.exe file.dots`, I get the following traceback:

```
Traceback (most recent call last):
  File "c:\users\tangil\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\tangil\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Tangil\AppData\Local\Programs\Python\Python37\Scripts\asciidots.exe\__main__.py", line 5, in <module>
  File "c:\users\tangil\appdata\local\programs\python\python37\lib\site-packages\dots\__main__.py", line 318
    def main(filename, ticks, silent, debug, compat_debug, debug_lines, autostep_debug, output_limit, async):
                                                                                                          ^
SyntaxError: invalid syntax
```

The `async` keyword should not be used in function arguments.

**Comment by TheBlocks** [comment]
I've fixed this in pull request #67.
