### ISSUE TITLE
Crash When Running Examples With Debug

### ISSUE THREAD

**Issue by padietl** [aaronduino/asciidots#9]
Running python3 __main__.py samples/counter.dots  -d -a 1
results in:

~/asciidots$ python3 __main__.py samples/counter.dots  -d -a 1
Traceback (most recent call last):
  File "__main__.py", line 253, in <module>
    main()
  File "/home/pdietl/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pdietl/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pdietl/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pdietl/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "__main__.py", line 249, in main
    raise e
  File "__main__.py", line 245, in main
    interpreter.run()
  File "/home/pdietl/asciidots/dots/interpreter.py", line 40, in run
    dot.simulate_tick()
  File "/home/pdietl/asciidots/dots/dot.py", line 79, in simulate_tick
    self.state.run(char)
  File "/home/pdietl/asciidots/dots/states.py", line 12, in _decorator
    func(self, *args, **kwargs)
  File "/home/pdietl/asciidots/dots/states.py", line 248, in run
    self.parent.callbacks.on_output(data)
  File "__main__.py", line 103, in on_output
    curses.LINES - 1, curses.COLS - 1)
_curses.error: prefresh() returned ERR

**Comment by aaronduino** [comment]
Try making the terminal full screen.

Does that fix the problem?

**Comment by padietl** [comment]
Unfortunately no. I have tried it at many sizes on OSX and on an Ubuntu VM

**Comment by aaronduino** [comment]
I think it has to do with the number of lines that can be displayed in the terminal.

Try cloning the most recent version of this repo and adding `-l 15` (that's an L for lines) to the command

**Comment by aaronduino** [comment]
You could even try changing that 15 to a 10.

**Comment by padietl** [comment]
Add it to the command like so?

python3 __main__.py samples/counter.dots -d -a 0.05 -l 15

**Comment by aaronduino** [comment]
Yes. It is a new command line flag that sets the number of lines to reserve for displaying the program.

If that doesn't work, try adding a `-w` flag before the last one (the lowercase L one)

**Comment by padietl** [comment]
~/asciidots$ python3 __main__.py samples/counter.dots -d -a 0.1 -w -l 15
Error: no such option: -l

However, if I run with the -w option (no -l), then it doesn't crash

**Comment by aaronduino** [comment]
Oops. I never pushed all my code to Github.

I just did. If you want, you can clone the latest version of this repo and get that flag.

Sorry for the hassle.

**Comment by padietl** [comment]
No problem! Yeah, that fixes the problem.

**Comment by aaronduino** [comment]
Great!

I think I will close this issue once I write code to automatically select the number of lines based on the number available.

Have fun with AsciiDots

**Comment by padietl** [comment]
Oh I definitely am.

**Comment by aaronduino** [comment]
Great
